<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>CA1707;CA1826;CA1001;CA1852</NoWarn>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Contracts/Ghost.Contracts.Jobs/Ghost.Contracts.Jobs.csproj" />
    <ProjectReference Include="../../src/Contracts/Ghost.Contracts.Social/Ghost.Contracts.Social.csproj" />
    <ProjectReference Include="../../src/Contracts/Ghost.Contracts.Inference/Ghost.Contracts.Inference.csproj" />
    <ProjectReference Include="../../src/Contracts/Ghost.Contracts.News/Ghost.Contracts.News.csproj" />
    <ProjectReference Include="../../src/Contracts/Ghost.Contracts.Simulation/Ghost.Contracts.Simulation.csproj" />
    <ProjectReference Include="../../src/Kernel/Ghost/Ghost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>

</Project>
