<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Ghostwright.Hosting.WebApi</RootNamespace>
    <Description>Ghostwright ASP.NET Core integration</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ghostwright.Hosting\Ghostwright.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
