<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Ghost.Plugin.Indeed</RootNamespace>
    <Description>Ghost Indeed plugin</Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
  </PropertyGroup>
  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1866;CA1310;CA1822;CA1707;CA1826;CA2201</NoWarn>
    <WarningsNotAsErrors>CA1866;CA1310;CA1822;CA1707;CA1826;CA2201</WarningsNotAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Kernel\Ghost\Ghost.csproj" />
    <ProjectReference Include="..\..\Sdk\Ghost.Sdk.Spider\Ghost.Sdk.Spider.csproj" />
    <ProjectReference Include="..\..\Contracts\Ghost.Contracts.Jobs\Ghost.Contracts.Jobs.csproj" />
    <ProjectReference Include="..\..\Contracts\Ghost.Contracts\Ghost.Contracts.csproj" />
    <ProjectReference Include="..\..\Platform\Hosting\Ghost.Hosting\Ghost.Hosting.csproj" />
    <ProjectReference Include="..\..\Platform\Storage\Ghost.Infrastructure.Session\Ghost.Infrastructure.Session.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
