<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Plugins/Ghost.Plugin.Glassdoor/Ghost.Plugin.Glassdoor.csproj" />
    <ProjectReference Include="../../../src/Contracts/Ghost.Contracts.Jobs/Ghost.Contracts.Jobs.csproj" />
    <ProjectReference Include="../../../src/Core/Ghost/Ghost.csproj" />
    <ProjectReference Include="../../../src/Infrastructure/Ghost.Infrastructure.Session/Ghost.Infrastructure.Session.csproj" />
    <ProjectReference Include="../../Shared/Ghost.Testing/Ghost.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

</Project>
