<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <LangVersion>preview</LangVersion>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Kernel/Ghost/Ghost.csproj" />
    <ProjectReference Include="../../../src/Sdk/Ghost.Sdk/Ghost.Sdk.csproj" />
    <ProjectReference Include="../../../src/Sdk/Ghost.Sdk.Spider/Ghost.Sdk.Spider.csproj" />
    <ProjectReference Include="../../Shared/Ghost.Testing/Ghost.Testing.csproj" />
    <ProjectReference Include="../../Shared/Ghost.Testing.Scenarios/Ghost.Testing.Scenarios.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />

  </ItemGroup>
</Project>
