<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="DotNetEnv" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\Ghost.Contracts.Jobs\Ghost.Contracts.Jobs.csproj" />
    <ProjectReference Include="..\..\Contracts\Ghost.Contracts.News\Ghost.Contracts.News.csproj" />
    <ProjectReference Include="..\..\Contracts\Ghost.Contracts.Social\Ghost.Contracts.Social.csproj" />
    <ProjectReference Include="..\..\Kernel\Ghost\Ghost.csproj" />
    <ProjectReference Include="..\..\Platform\Hosting\Ghost.Hosting\Ghost.Hosting.csproj" />
    <ProjectReference Include="..\..\Platform\Hosting\Ghost.Hosting.WebApi\Ghost.Hosting.WebApi.csproj" />
    <ProjectReference Include="..\..\Plugins\LinkedIn\Ghost.Plugin.LinkedIn\Ghost.Plugin.LinkedIn.csproj" />
    <ProjectReference Include="..\..\Plugins\Anthropic\Ghost.Plugin.Anthropic\Ghost.Plugin.Anthropic.csproj" />
    <ProjectReference Include="..\..\Plugins\Google\Ghost.Plugin.Google\Ghost.Plugin.Google.csproj" />
    <ProjectReference Include="..\..\Plugins\OpenAI\Ghost.Plugin.OpenAI\Ghost.Plugin.OpenAI.csproj" />
    <ProjectReference Include="..\..\Plugins\Indeed\Ghost.Plugin.Indeed\Ghost.Plugin.Indeed.csproj" />
    <ProjectReference Include="..\..\Plugins\Glassdoor\Ghost.Plugin.Glassdoor\Ghost.Plugin.Glassdoor.csproj" />
  </ItemGroup>

</Project>
