<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/Platforms/Ghost.Platform.LinkedIn/Ghost.Platform.LinkedIn.csproj" />
    <ProjectReference Include="../src/SDK/Ghost.Sdk.Spider/Ghost.Sdk.Spider.csproj" />
    <ProjectReference Include="../src/Core/Ghost/Ghost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
    <PackageReference Include="Microsoft.Playwright" Version="1.49.1" />
  </ItemGroup>
</Project>
