<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Ghost.Engine</RootNamespace>
    <Description>Ghost engine runtime implementation</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ghost.Engine.Abstractions\Ghost.Engine.Abstractions.csproj" />
  </ItemGroup>
</Project>
