<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Ghost.Scraper.DotnetSpider</RootNamespace>
    <AssemblyName>Ghost.Scraper.DotnetSpider</AssemblyName>
    <Description>Ghost DotnetSpider scraper framework integration</Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Platforms/Ghost.Platform.Common/Ghost.Platform.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotnetSpider" />
    <PackageReference Include="Polly" />
  </ItemGroup>

</Project>
