<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ghost.Contracts.Simulation</RootNamespace>
    <Description>Ghost simulation framework contracts</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ghost.Contracts.Social\Ghost.Contracts.Social.csproj" />
  </ItemGroup>

</Project>
